from __future__ import annotations

import logging

from botcheck_observability.circuit_breaker import (
    PROVIDER_CIRCUIT_REJECTIONS_TOTAL,
    PROVIDER_CIRCUIT_STATE,
    PROVIDER_CIRCUIT_TRANSITIONS_TOTAL,
    set_provider_circuit_state,
)
from botcheck_observability.helpers import (
    counter as _counter,
    gauge as _gauge,
    histogram as _histogram,
)
from botcheck_observability.provider import (
    PROVIDER_API_CALLS_TOTAL,
    STT_SECONDS_TOTAL,
    TELEPHONY_MINUTES_TOTAL,
    TTS_CHARACTERS_TOTAL,
)
from prometheus_client import start_http_server

from .config import settings

logger = logging.getLogger("botcheck.agent.metrics")
_METRICS_SERVER_STARTED = False


AGENT_RUNS_TOTAL = _counter(
    "botcheck_agent_runs_total",
    "Harness run outcomes.",
    ["outcome"],
)

AGENT_RUN_DURATION_SECONDS = _histogram(
    "botcheck_agent_run_duration_seconds",
    "Harness run duration in seconds.",
    ["outcome"],
    buckets=(0.5, 1, 2, 5, 10, 20, 40, 80, 120, 240, 480),
)

AGENT_TURNS_TOTAL = _counter(
    "botcheck_agent_turns_total",
    "Conversation turns generated by harness.",
    ["speaker", "outcome"],
)

AGENT_API_CALLBACKS_TOTAL = _counter(
    "botcheck_agent_api_callbacks_total",
    "Result of harness callback requests to API endpoints.",
    ["endpoint", "outcome"],
)

AGENT_FINAL_ACK_TOTAL = _counter(
    "botcheck_agent_final_ack_total",
    "Result of greedy final acknowledgement attempts.",
    ["outcome"],
)

STT_LISTEN_LATENCY_SECONDS = _histogram(
    "botcheck_stt_listen_latency_seconds",
    "End-to-end latency for a bot STT listen cycle in seconds.",
    ["provider", "model", "result", "scenario_kind"],
    buckets=(0.1, 0.25, 0.5, 0.75, 1, 1.5, 2, 3, 5, 8, 12),
)

TTS_PLAYBACK_LATENCY_SECONDS = _histogram(
    "botcheck_tts_playback_latency_seconds",
    "Latency from harness speech start to final audio frame publish in seconds.",
    ["provider", "model", "source", "scenario_kind"],
    buckets=(0.05, 0.1, 0.2, 0.4, 0.8, 1.2, 2, 3, 5, 8),
)

TTS_FIRST_BYTE_LATENCY_SECONDS = _histogram(
    "botcheck_tts_first_byte_latency_seconds",
    "Latency from live TTS request start to first audio frame in seconds.",
    ["provider", "model", "scenario_kind"],
    buckets=(0.05, 0.1, 0.2, 0.4, 0.8, 1.2, 2, 3, 5, 8),
)

TTS_STREAM_DURATION_SECONDS = _histogram(
    "botcheck_tts_stream_duration_seconds",
    "Latency from first live TTS audio frame to final frame in seconds.",
    ["provider", "model", "scenario_kind"],
    buckets=(0.05, 0.1, 0.2, 0.4, 0.8, 1.2, 2, 3, 5, 8),
)

TTS_PLAYBACK_CANCELLATIONS_TOTAL = _counter(
    "botcheck_tts_playback_cancellations_total",
    "Harness playback cancellations before or during audio publish.",
    ["provider", "model", "source", "reason", "scenario_kind"],
    # reason values: pre_start | in_flight | task_cancelled
)

TTS_LIVE_FAILURES_TOTAL = _counter(
    "botcheck_tts_live_failures_total",
    "Live TTS synthesis failures by failure reason.",
    ["provider", "model", "reason", "scenario_kind"],
    # reason values: timeout | circuit_open | error
)

# Phase 40.1 AI-loop stage latency histograms.
# "Bot turn end" in all descriptions below means the moment the STT window closes
# (BotListener.listen() returns), not the audio waveform end. This can trail real
# speech end by up to stt_endpointing_ms milliseconds. Keep this in mind when
# interpreting Phase 40.6 benchmarks against the native speech baseline.
# Label sets: opening_strategy, scenario_kind shared across all four; source and
# (for the LLM gap) LLM-path-only metrics intentionally omit the source label.
AI_CALLER_REPLY_LATENCY_SECONDS = _histogram(
    "botcheck_ai_caller_reply_latency_seconds",
    "Latency from bot turn end (STT window close) to next caller utterance start.",
    ["opening_strategy", "source", "scenario_kind"],
    buckets=(0.05, 0.1, 0.2, 0.4, 0.8, 1.2, 2, 3, 5, 8),
)

AI_CALLER_DECISION_LATENCY_SECONDS = _histogram(
    "botcheck_ai_caller_decision_latency_seconds",
    "Latency from bot turn end (STT window close) to next caller decision ready.",
    ["opening_strategy", "source", "scenario_kind"],
    buckets=(0.01, 0.05, 0.1, 0.2, 0.4, 0.8, 1.2, 2, 3, 5, 8),
)

AI_CALLER_LLM_REQUEST_START_GAP_SECONDS = _histogram(
    "botcheck_ai_caller_llm_request_start_gap_seconds",
    "Latency from bot turn end (STT window close) to AI caller LLM request start.",
    ["opening_strategy", "scenario_kind"],
    buckets=(0.01, 0.05, 0.1, 0.2, 0.4, 0.8, 1.2, 2, 3, 5, 8),
)

AI_CALLER_DECISION_TO_PLAYBACK_START_GAP_SECONDS = _histogram(
    "botcheck_ai_caller_decision_to_playback_start_gap_seconds",
    "Latency from caller decision ready to harness playback start.",
    ["opening_strategy", "source", "scenario_kind"],
    buckets=(0.01, 0.05, 0.1, 0.2, 0.4, 0.8, 1.2, 2, 3, 5, 8),
)

AI_VOICE_PREVIEW_EVENTS_TOTAL = _counter(
    "botcheck_ai_voice_preview_events_total",
    "Preview transcript events surfaced during voice AI listen windows.",
    ["event_type", "scenario_kind"],
)

AI_VOICE_SPECULATIVE_PLANS_TOTAL = _counter(
    "botcheck_ai_voice_speculative_plans_total",
    "Speculative AI caller planning outcomes from preview transcripts.",
    ["outcome", "scenario_kind"],
)

AI_VOICE_FAST_ACK_TOTAL = _counter(
    "botcheck_ai_voice_fast_ack_total",
    "Fast-ack fallbacks that start the first AI caller turn before LLM completion.",
    ["source", "opening_strategy", "scenario_kind"],
    # source values: dataset_input | heuristic
)

AI_VOICE_EARLY_PLAYBACK_TOTAL = _counter(
    "botcheck_ai_voice_early_playback_total",
    "Early speculative playback outcomes for the first AI caller turn.",
    ["outcome", "scenario_kind"],
    # outcome values: started | committed | stale_suppressed | cancelled | error
)

SIP_CALL_OUTCOMES_TOTAL = _counter(
    "botcheck_sip_call_outcomes_total",
    "Per-call SIP outcomes recorded by the harness agent.",
    ["outcome"],
    # outcome values:
    #   answered   – SIP participant joined the room (call was picked up)
    #   no_answer  – timed out waiting for SIP participant to join
    #   completed  – scenario ran to end with SIP participant present
    #   dropped    – SIP participant disconnected mid-scenario
)

SIP_CALL_DURATION_SECONDS = _histogram(
    "botcheck_sip_call_duration_seconds",
    "Duration of SIP calls from participant join to scenario end.",
    [],
    buckets=(5, 10, 20, 30, 60, 90, 120, 180, 300, 480),
)

TTS_CACHE_HITS_TOTAL = _counter(
    "botcheck_tts_cache_hits_total",
    "Successful TTS cache reads in harness.",
    ["scenario_kind"],
)

TTS_CACHE_MISSES_TOTAL = _counter(
    "botcheck_tts_cache_misses_total",
    "TTS cache key-absent reads in harness.",
    ["scenario_kind"],
)

TTS_CACHE_FALLBACK_TOTAL = _counter(
    "botcheck_tts_cache_fallback_total",
    "Harness fallbacks to live TTS due to cache read/service errors.",
    ["reason"],
)

BRANCH_CLASSIFIER_CALLS_TOTAL = _counter(
    "botcheck_branch_classifier_calls_total",
    "Branch classifier call outcomes.",
    ["outcome"],
)

BRANCH_CLASSIFIER_LATENCY_SECONDS = _histogram(
    "botcheck_branch_classifier_latency_seconds",
    "Branch classifier latency in seconds.",
    ["outcome"],
    buckets=(0.05, 0.1, 0.2, 0.4, 0.8, 1.2, 1.5, 2, 3, 5),
)

def start_metrics_server_if_enabled() -> None:
    global _METRICS_SERVER_STARTED
    if not settings.metrics_enabled or _METRICS_SERVER_STARTED:
        return
    start_http_server(addr=settings.metrics_host, port=settings.metrics_port)
    _METRICS_SERVER_STARTED = True
    logger.info(
        "Agent metrics endpoint started on %s:%s",
        settings.metrics_host,
        settings.metrics_port,
    )
