"""Compatibility facade for shared store-service symbols.

Canonical implementations now live in feature-local modules:
- scenarios/store_service.py
- runs/store_service.py
- packs/service.py
"""

from __future__ import annotations

from ..packs.service import (
    DestinationUsageResult,
    PackRunCancelResult,
    PackRunChildAggregateResult,
    PackRunDispatchStartResult,
    PackRunMarkFailedResult,
    PackRunSnapshot,
    StoredBotDestination,
    StoredScenarioPack,
    StoredScenarioPackItem,
    aggregate_pack_run_child_terminal_state,
    cancel_pack_run,
    create_or_replace_bot_destination,
    create_or_replace_scenario_pack,
    create_pack_run_snapshot,
    delete_bot_destination,
    delete_scenario_pack,
    get_active_pack_run_by_idempotency,
    get_bot_destination,
    get_destination_usage,
    get_pack_run_for_tenant,
    get_previous_pack_run_for_tenant_pack,
    get_scenario_pack,
    has_active_pack_runs_for_pack,
    list_bot_destinations,
    list_destination_usage,
    list_pack_run_items,
    list_pack_runs_for_tenant,
    list_scenario_packs,
    mark_pack_run_failed,
    start_pack_run_dispatch,
)
from ..runs.store_service import (
    append_run_event,
    append_turn,
    get_run,
    get_run_for_tenant,
    get_schedule_for_tenant,
    list_active_runs,
    list_due_schedules,
    list_running_runs,
    list_runs_by_ids,
    list_schedules,
    store_run,
    store_schedule,
    update_run_state,
)
from ..scenarios.store_service import (
    ScenarioCacheRebuildRequest,
    ScenarioCacheSyncResult,
    StoredAIPersona,
    StoredAIScenario,
    StoredAIScenarioRecord,
    StoredAIScenarioSummary,
    StoredScenario,
    ai_persona_in_use,
    create_or_replace_ai_persona,
    create_or_replace_ai_scenario,
    create_or_replace_ai_scenario_record,
    delete_ai_persona,
    delete_ai_scenario,
    delete_ai_scenario_record,
    delete_scenario,
    get_ai_persona,
    get_preferred_ai_scenario_record_for_dispatch,
    get_ai_scenario,
    get_ai_scenario_by_scenario_id,
    get_scenario,
    get_scenario_cache_status,
    get_scenario_kind,
    get_scenario_yaml,
    has_schedules_for_scenario,
    list_ai_personas,
    list_ai_scenario_records,
    list_ai_scenarios,
    list_scenarios,
    queue_scenario_cache_rebuild,
    sanitize_ai_scenario_config,
    store_scenario,
    sync_scenario_cache_status,
)

__all__ = [
    # packs
    "DestinationUsageResult",
    "PackRunCancelResult",
    "PackRunChildAggregateResult",
    "PackRunDispatchStartResult",
    "PackRunMarkFailedResult",
    "PackRunSnapshot",
    "StoredBotDestination",
    "StoredScenarioPack",
    "StoredScenarioPackItem",
    "aggregate_pack_run_child_terminal_state",
    "cancel_pack_run",
    "create_or_replace_bot_destination",
    "create_or_replace_scenario_pack",
    "create_pack_run_snapshot",
    "delete_bot_destination",
    "delete_scenario_pack",
    "get_active_pack_run_by_idempotency",
    "get_bot_destination",
    "get_destination_usage",
    "get_pack_run_for_tenant",
    "get_previous_pack_run_for_tenant_pack",
    "get_scenario_pack",
    "has_active_pack_runs_for_pack",
    "list_bot_destinations",
    "list_destination_usage",
    "list_pack_run_items",
    "list_pack_runs_for_tenant",
    "list_scenario_packs",
    "mark_pack_run_failed",
    "start_pack_run_dispatch",
    # runs
    "append_run_event",
    "append_turn",
    "get_run",
    "get_run_for_tenant",
    "get_schedule_for_tenant",
    "list_active_runs",
    "list_due_schedules",
    "list_running_runs",
    "list_runs_by_ids",
    "list_schedules",
    "store_run",
    "store_schedule",
    "update_run_state",
    # scenarios
    "ScenarioCacheRebuildRequest",
    "ScenarioCacheSyncResult",
    "StoredAIPersona",
    "StoredAIScenario",
    "StoredAIScenarioRecord",
    "StoredAIScenarioSummary",
    "StoredScenario",
    "ai_persona_in_use",
    "create_or_replace_ai_persona",
    "create_or_replace_ai_scenario",
    "create_or_replace_ai_scenario_record",
    "delete_ai_persona",
    "delete_ai_scenario",
    "delete_ai_scenario_record",
    "delete_scenario",
    "get_ai_persona",
    "get_preferred_ai_scenario_record_for_dispatch",
    "get_ai_scenario",
    "get_ai_scenario_by_scenario_id",
    "get_scenario",
    "get_scenario_cache_status",
    "get_scenario_kind",
    "get_scenario_yaml",
    "has_schedules_for_scenario",
    "list_ai_personas",
    "list_ai_scenario_records",
    "list_ai_scenarios",
    "list_scenarios",
    "queue_scenario_cache_rebuild",
    "sanitize_ai_scenario_config",
    "store_scenario",
    "sync_scenario_cache_status",
]
